---
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: main
  namespace: monitoring
  labels:
    alertmanager: main
spec:
  route:
    groupBy: ["alertname"]
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 12h
    receiver: slack-notifications
    routes:
      - receiver: slack-notifications
        match:
          severity: warning
  receivers:
    - name: slack-notifications
      slackConfigs:
        - channel: "#alerts"
          sendResolved: true
          apiURL:
            name: slack
            key: slack-url
          text: "{{ range .Alerts }}<!channel> {{ .Annotations.summary }}\n{{ .Annotations.description }}\n{{ end }}"
