---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: myapp
  namespace: monitoring
  labels:
    component: main
spec:
  namespaceSelector:
    matchNames:
      - staging
  selector:
    matchLabels:
      name: myapp
  podMetricsEndpoints:
    - port: http-metrics
      path: /metrics
